apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secrets
data:
  # The following users are required by Patroni:
  PATRONI_SUPERUSER_PASSWORD: <BASE64_ENCODED_SUPERUSER_PASSWORD>
  PATRONI_REPLICATION_PASSWORD: <BASE64_ENCODED_REPLICATION_PASSWORD>
  # Add additional PG user credentials in the form of
  # PATRONI_<username>_PASSWORD=<BASE64_ENCODED_PASSWORD>
  # and Patroni will automatically create these on first deployment.
  # For example:
  # PATRONI_admin_PASSWORD: <BASE64_ENCODED_ADMIN_PASSWORD>
  # PATRONI_admin_OPTIONS: <BASE64_ENCODED_ADMIN_OPTIONS>
  # PGBACKREST_REPO1_S3_KEY: <BASE64_ENCODED_REPO1_S3_KEY>
  # PGBACKREST_REPO1_S3_KEY_SECRET: <BASE64_ENCODED_REPO1_S3_KEY_SECRET>
  # TIMESCALEDB_LICENSE_KEY: <BASE64_ENCODED_LICENSE_KEY>
